myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from mysite.core import views


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('upload/', views.upload, name='upload'),
    path('books/', views.book_list, name='book_list'),
    path('books/', views.upload_book, name='book_list'),
     path('books/upload/', views.upload_book, name='book_upload'),
    path('books/<int:pk>/', views.delete_book, name='delete_book'),

    path('class/books/', views.BookListView.as_view(), name='class_book_list'),
    path('class/books/upload/', views.UploadBookView.as_view(), name='class_upload_book'),

    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/core/models.py
from django.db import models


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    pdf = models.FileField(upload_to='books/pdfs/')
    cover = models.ImageField(upload_to='books/covers/', null=True, blank=True)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.pdf.delete()
        self.cover.delete()
        super().delete(*args, **kwargs)

mysite/core/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'author', 'pdf','cover')

mysite/core/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView, ListView, CreateView
from django.core.files.storage import FileSystemStorage
from django.urls import reverse_lazy

import pandas as pd

from .forms import BookForm
from .models import Book

pr = pd.read_csv(
    'media/Pasta1.csv',
    encoding='utf8',
    sep=';'
)
print(pr.head())


class Home(TemplateView):
    template_name = 'home.html'


def upload(request):
    context = {}
    if request.method == 'POST':
        uploaded_file = request.FILES['document']
        fs = FileSystemStorage()
        name = fs.save(uploaded_file.name, uploaded_file)
        context['url'] = fs.url(name)

    return render(request, 'upload.html', context)





def book_list(request):
    books = Book.objects.all()
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = BookForm()       
    return render(request, 'book_list.html', {
        'books': books
    })


def upload_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('book_list')
    else:
        form = BookForm()
    return render(request, 'upload_book.html', {
        'form': form
    })


def delete_book(request, pk):
    if request.method == 'POST':
        book = Book.objects.get(pk=pk)
        book.delete()
    return redirect('book_list')


class BookListView(ListView):
    model = Book
    template_name = 'class_book_list.html'
    context_object_name = 'books'



class UploadBookView(CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('class_book_list')
    template_name = 'upload_book.html'

mysite/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'css/app.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/blog.rtl.css' %}">
  <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/blog/">
  <style>
    body {
      background-color: #fff;
     }

     #input-ano{
      margin-left: 35%;
      margin-top: -3%;
      width: 56%;
     }

     #select {
      display: flex;
      text-transform: none;
      margin-top: 5%;
      margin-left: 16%;
      height: 30px;
      width: 150px;
  }
     .blog-header {
      
      border-bottom: none;
    }
    #navbar{
      margin-left: 16%;
      margin-top: -3%;
      font-size: 24px;
    }

    #navbarSupportedContent{
      color: #0d6efd;
    }
   
    #btn-upload{
      margin-left: 40%;
      display: flex;
      margin-top: 5%;
    }

    #input-file{
      padding-top: 1%;
    }

    
    .card-body{
    height: 250px;
    }

    .card-csv{
      height: 221px;
      width: 800px;
      }

    .footer{
      
      width: 100%;
      display: none;
      position: fixed;
      bottom: 0;
      left: 0;
    }

    #id_pdf{
      padding-top: 1%;
      margin-left: 35%;
    }

    #id_title{
      width: 21%;
      margin-top: 42px;
      margin-left: 10%;
      height: 35px;

    }

    #id_author{
      width: 33%;
      margin-top: 42px;
      margin-left: 10%;
      height: 20%;
    }

    .b{
      margin-left: 35%;
      margin-top: 35px;
    }

    #tabela{
      margin-top: 80px;
    }

    #organize{
      display: flex;
    }

    #url{
      
      height: 100%;
      font-family: sans-serif
    }

    .align-items-center{
      align-items: none;
    }
    
    #Logo {
      vertical-align: middle;
      border-style: none;
      padding-left: 15%;
      padding-top: 5%;
    }
    #upload{
      display: flex;
    }
  </style>
  <title>{% block title %}My Site{% endblock %}</title>
</head>
<body>
  <header class="blog-header py-3">
    <div class="row flex-nowrap justify-content-between align-items-center">
      <div class="col-4 pt-1">
        <img id="Logo" src="{% static 'assets/logo-projeto.png' %}" alt="Logo">
      </div>
      <div class="col-4 text-center">
        <a class="blog-header-logo text-dark" href="#">Sair</a>
      </div>
    
  </header>

  <nav class="navbar navbar-expand-lg  mb-4" id="navbar" style="background-color:#fff">
    <div class="container">
      
      <div class="collapse navbar-collapse" id="navbarSupportedContent" style="color:#0d6efd">

        <ul class="navbar-nav"  id="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">INÍCIO |</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">APRESENTAÇÃO |</a>
            
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'upload' %}">METODOLOGIA |</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'book_list' %}">EQUIPE TÉCNICA |</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'class_book_list' %}">CONTATOS </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10 col-md-12">
        <div class="card mb-4">
          <div class="card-body">
            {% block content %}
            {% endblock %}
          </div>
        </div>
      </div>
    </div>
  </div>

 
  <footer class="footer">
    <h2>Desenvolvido por Codamais &copy; 2022</h2>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

mysite/templates/book_list.html
{% extends 'base.html' %}


{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   
    <input type="hidden" name="csrfmiddlewaretoken" value="Q8d71q4TCTbHG3uVjxtCOXqaVxMqVX37pPWymG6K9m4BZVJYhZ9utVgxJ4QRNWF6">
    <input type="file" name="pdf" class="clearablefileinput" required="" id="id_pdf">

    <div id="organize">

      <select class="form-select" aria-label="Default select example" name="title" id="id_title">
        <option selected >SELECIONE</option>
        <option value="MEI">MEI</option>
        <option value="SUBSEQ">SUBSEQ</option>
        
      </select>
    


    <input type="text" name="author" maxlength="100" class="textinput textInput form-control" required="" id="id_author" placeholder="ANO DE REFERÊNCIA (CONCLUSÃO)">
    </div>


   
    <button type="submit" class="b">CARREGAR DADOS</button>
  </form>


  <table class="table mb-0" id="tabela">
    <thead>
      <tr>
        <th>NOME DA BASE</th>
        <th>DATA UPLOAD</th>
        <th>EDIÇÃO</th>
      </tr>
    </thead>
    <tbody>
      {% for book in books %}

      
        <tr>

          <td >
            <a id="url" href="{{ book.pdf.url }}">{{ book.pdf }}</a>
           
          </td>
          <td>{{ book.author }}</td>
          <td>
            <form method="post" action="{% url 'delete_book' book.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

mysite/templates/class_book_list.html
{% extends 'book_list.html' %}

{% block content_header %}
  <h2>Books (Class-Based View)</h2>
  <p>
    <a href="{% url 'class_upload_book' %}" class="btn btn-primary">Upload book</a>
  </p>
{% endblock %}

mysite/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h2 class="card-title">Django File Upload Tutorial</h2>
  <p class="card-text">Example Django 2.1 / Python 3.7</p>
  <p class="card-text">
    Watch it on <a href="#">YouTube</a> or
    read the <a href="https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html">Blog Post</a>.
  </p>
  <p class="card-text">
    Codamais EJ<br>
    <a href="#">@Codamais</a>
  </p>
{% endblock %}

mysite/templates/upload.html
{% extends 'base.html' %}

{% block content %}
  
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <input type="file" name="document" id="input-file" style="margin-left: 35%;">

    <select class="form-select" id="select"  aria-label="Default select example">
      <option selected>SELECIONE</option>
      <option value="1">MEI</option>
      <option value="2">SUBSE</option>
    </select>

    <div class="input" id="input-ano">
      <input type="text" id="input-ano" placeholder="ANO DE REFERÊNCIA (CONCLUSÃO)">
    </div>

    <button type="submit" id="btn-upload" >Upload file</button>
  </form>
  {% if url %}
    <p>Uploaded file: <a href="{{ url }}">{{ url }}</a></p>
  {% endif %}
{% endblock %}

mysite/templates/upload_book.html
{% extends 'base.html' %}


{% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
   
    <input type="hidden" name="csrfmiddlewaretoken" value="Q8d71q4TCTbHG3uVjxtCOXqaVxMqVX37pPWymG6K9m4BZVJYhZ9utVgxJ4QRNWF6">

    <input type="text" name="title" maxlength="100" class="textinput textInput form-control" required="" id="id_title">


   <input type="text" name="author" maxlength="100" class="textinput textInput form-control" required="" id="id_author">



   <input type="file" name="pdf" class="clearablefileinput" required="" id="id_pdf">
    <button type="submit" class="b">Upload book</button>
  </form>


  
{% endblock %}